### ISSUE TITLE
Bad Zip files

### ISSUE THREAD

**Issue by Gabya06** [johnb30/gdelt_download#3]
I'm trying to run the historical script and it's creating all the files but I cant seem to unzip any of them, if I try I get a file like '1979.zip.cpgz'. I also tried running it as a single year and am getting the same error 'Bad zip file'.

**Comment by johnb30** [comment]
I'm no longer associated with the GDELT project (see [here](http://blog.gdelt.org/2014/01/20/gdelt-suspension/)). The issue is that the data is no longer hosted on the UT-Dallas servers, so there is nothing for the script to download. I'm not going to update the scripts, but the only thing that needs to change are the URLs.

**Comment by Gabya06** [comment]
Thanks for the reply, this helps.
